### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by eddiejaoude**

### CODE REVIEW

**Comment by rohan-kulkarni-25** [comment]
Yes, that will be easy for everyone to know what is the project for !!

**Comment by kaiwalyakoparkar** [comment]
@rohank2502 This is not technically a project. This are just configuration files.

**Comment by eddiejaoude** [comment]
I think every repo should have a README though with more info

**Comment by kaiwalyakoparkar** [comment]
Most definitely. I just saw the file. I actually write readmes so that I can recall how to make the project running on locale system after a long break to it. (I was just trying to clear the concept of rohan.)

**Pull request closed without merging**
